version: '3.9'

services:
  # Сервис для разворачивания контейнера с базой данных
  database:
    image: postgres:latest
    user: postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=super
      - POSTGRES_DB=dncDB
    ports:
      - "5432"

  # Сервис для разворачивания контейнера с приложением
  webapi:
    pull_policy: always
    image: jiln3hb/planet-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/dncDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super


  # Сервис для разворачивания контейнера с автотестами
  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:80
      STAGE: all
      # all - запуск всех тестов из трёх доступных этапов
      # 0, 1 или 2 - запуск тестов для соответствующего этапа
